### ISSUE TITLE
Locale Selector

### ISSUE THREAD

**Issue by TTWNO** [eeejay/spiel#15]
There should be a locale identifier whenever sending speech commands, I propose:

```text
Speak (
  IN task_id t,
  IN text s,
  IN voice_id s,
  IN pitch d,
  IN rate d,
- IN volume d
+ IN volume d,
+ IN locale_id s
)
```

As far as I can tell, a single voice may support multiple languages, so when sending text, a language must be specified. If the locale ID can mimic the IDs often seen in HTTP requests, that would at least be familiar to most developers.

**Comment by eeejay** [comment]
i assume the local_id would be identical to one of the strings returned in the `languages` array in `GetVoices()`
