### ISSUE TITLE
Support SSML, or at least a subset

### ISSUE THREAD

**Issue by eeejay** [eeejay/spiel#16]
Screen readers need to have the ability to spell out words. Instead of introducing new API for this, we should support this markup:
```xml
<say-as interpret-as="characters">can</say-as>
```

**Comment by eeejay** [comment]
I'm not suggesting libspiel parse XML, instead we need to add SSML to the spec so that speech providers do it.

**Comment by alcinnz** [comment]
This feature would really pique my interest in LibSpiel!

**Comment by TTWNO** [comment]
I'm fully in support of this. SSML makes screen readers *much* more flexible.

Being able to directly map data into SSML, instead of guessing how each provider will interpret the text, being able to use a per-existing markup standard would be outstanding!

Even if only passthrough-based SSML works (with an API for checking if it's supported by the voice), I'd be thrilled!

**Comment by eeejay** [comment]
So there are two parts to this support, client (libspiel), and provider interface.

From the libspiel perspective, I think `Utterance` objects should have a `SSML` boolean property. If set, the utterance should be considered SSML and should be parsed as such.

From the providers side, each voice should return a bitmap field of capabilities. SSML features should be broken up into capabilities. A provider that supports SSML should parse the markup given and remove any unsupported tags. Here are the SSML capabilities each voice can advertise:
* `VOICE_SUPPORTS_SSML_SAY_AS_DATE`: Support `<say-as interpret-as="date">` as specified in the [W3C note](https://www.w3.org/TR/ssml-sayas/).
* `VOICE_SUPPORTS_SSML_SAY_AS_TIME`:  Support `<say-as interpret-as="time">` as specified in the [W3C note](https://www.w3.org/TR/ssml-sayas/).
* `VOICE_SUPPORTS_SSML_SAY_AS_TELEPHONE`: Support `<say-as interpret-as="telephone">` as specified in the [W3C note](https://www.w3.org/TR/ssml-sayas/).
* `VOICE_SUPPORTS_SSML_SAY_AS_CHARACTERS`: Support `<say-as interpret-as="characters">` as specified in the [W3C note](https://www.w3.org/TR/ssml-sayas/), excluding `format="glyphs"`
* `VOICE_SUPPORTS_SSML_SAY_AS_CHARACTERS_GLYPHS`: Support `<say-as interpret-as="characters">` as specified in the [W3C note](https://www.w3.org/TR/ssml-sayas/), including `format="glyphs"`
* `VOICE_SUPPORTS_SSML_SAY_AS_CARDINAL`:  Support `<say-as interpret-as="cardinal">` as specified in the [W3C note](https://www.w3.org/TR/ssml-sayas/).
* `VOICE_SUPPORTS_SSML_SAY_AS_ORDINAL`:  Support `<say-as interpret-as="ordinal">` as specified in the [W3C note](https://www.w3.org/TR/ssml-sayas/).
* `VOICE_SUPPORTS_SSML_SAY_AS_CURRENCY`:  Support `<say-as interpret-as="currency">`.
* `VOICE_SUPPORTS_SSML_BREAK`: Support `<break>`
* `VOICE_SUPPORTS_SSML_SUB`: Support `<sub>`
* `VOICE_SUPPORTS_SSML_PHONEME`: Support `<phoneme>` with the IPA dictionary
* `VOICE_SUPPORTS_SSML_EMPHASIS`: Support `<emphasis>`
* `VOICE_SUPPORTS_SSML_PROSODY`: Support `<prosody>` with rate, pitch, and volume.
* `VOICE_SUPPORTS_SSML_MARK`: Support `<mark>` events.
* `VOICE_SUPPORTS_SSML_SENTENCE_PARAGRAPH`: Support `<s>` and `<p>`.
* `VOICE_SUPPORTS_SSML_TOKEN`: Support `<token>`

There are some SSML features that duplicate Spiel's features. For now they will be left out, but in the future Spiel could do its own XML parsing and enable this markup. For example, `<voice lang="ar">` would use Spiel's voice selection algorithm to pick the best voice of Arabic and create a composite multi-voice sequence. Another omission is `<audio>` since it is outside the scope of this library, but in the future we can parse that tag and play audio interleaved with speech. For now, libspiel users can play their own audio through other APIs.
