### ISSUE TITLE
Consider supporting context of content to be spoken (if possible)

### ISSUE THREAD

**Issue by joanmarie** [eeejay/spiel#24]
Example use cases:

* A screen-reader user is arrowing character by character and reaches `-`. When that single character is sent to the speech provider to be spoken, should the result be "dash"/"hyphen" or "minus"?
* A browser user (with web speech or with a screen reader) reaches a line of text which contains a `²`: should it be "superscript 2" or "squared" or maybe even "footnote 2"?
* As I learned through [an issue filed against Orca](https://gitlab.gnome.org/GNOME/orca/-/issues/314), "When reading an article in the 'Journal of chemistry', 'Ga' means 'Gallium', but in an encyclical letter in French, it means 'Galates'."

Orca [now](https://gitlab.gnome.org/GNOME/orca/-/issues/313) defers to the speech provider for character names -- with the exception of content it believes to be math (right now limited to MathML). In the latter case, Orca looks up the character in its own dictionary of math symbols and sends the localized character name to the speech provider.

My goal, if possible, is to stop doing even that substitution. It would be great if instead I could somehow indicate the nature of the content and let the speech provider / synthesizer handle it appropriately.

I realize this is all easier said then done, but... Thoughts?

**Comment by eeejay** [comment]
I'm going to close this since a lot of this was addressed with the introduction of SSML.
