### ISSUE TITLE
Allow streaming of synthesized audio back to client

### ISSUE THREAD

**Issue by eeejay** [eeejay/spiel#8]
Draft a spec and allow speech providers to send audio data back to the client instead of piping it out to the default audio device.

**Comment by TheMuso** [comment]
It is worth noting that GStreamer has a few elements that allow sending audio via IPC. Shared memory and memfd is supported, as well as using file descriptors or maybe sockets, I'd have to check.

**Comment by TTWNO** [comment]
This will be restricted by licenses of the voices themselves, otherwise proprietary voices will not work with a library that allows this on all voices, without restriction.

cc: https://github.com/brailcom/speechd/issues/348

**Comment by eeejay** [comment]
Fascinating. Do you know what synthesizer they were referencing? I think its interesting that they don't have a speechd output module, were there other licensing restrictions that prevented this?

**Comment by TTWNO** [comment]
Likely vocalizer, which is a proprietary (but often used) TTS on Linux due to its high quality.

It's the default set of voices on iOS and MacOS.

**Comment by TheMuso** [comment]
I also found the same restrictions when I was looking into the Cepstral synthesizer API years back when considering adding support for it to Speech Dispatcher.

**Comment by eeejay** [comment]
from what i can tell there is no technical issue, voxin voices let you write audio to buffers. I think there is a legal interpretation issue perhaps? We aren't going to write the audio data to files, but to output streams. Yes, a consumer of libspiel will be able to write to file if they choose, but i don't know who would be violating the license at that point. Our API would not allow anything the synthesizer's API doesn't.

**Comment by eeejay** [comment]
@TheMuso Did you actually speak to someone there about it? I'm curious to know exactly what restrictions they impose and what we can do to remedy it.

**Comment by TheMuso** [comment]
No, I didn't speak to anyone. I remember reading about the restrictions either on the website, or the SDK. This was many years back, things may have changed, have not looked again since.
